### ISSUE TITLE
Cannot start registry in standalone mode

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#111]
Steps:

- Fresh clone of Registry
- Windows 10 (dotnet core 5)

`dotnet run --project Registry.Web --urls http://0.0.0.0`

```
D:\RegistryApp>dotnet run --project Registry.Web --urls http://0.0.0.0
 !> Using DDB version 0.9.8 (git commit 4e737c0)
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\pt\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.ArgumentException: Option 'mode' not supported.
         at MySqlConnector.MySqlConnectionStringOption.GetOptionForKey(String key) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 478
         at MySqlConnector.MySqlConnectionStringBuilder.set_Item(String key, Object value) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 379
         at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
         at MySqlConnector.MySqlConnectionStringBuilder..ctor(String connectionString) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 19
         at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
         at Registry.Web.Startup.<>c__DisplayClass12_0`1.<ConfigureDbProvider>b__0(DbContextOptionsBuilder options) in D:\RegistryApp\Registry.Web\Startup.cs:line 520
         at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider p, DbContextOptionsBuilder b)
         at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
         at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
...
``` 

:boom: 

I think it's probably because the default DB has been set to MySQL.

**Comment by HeDo88TH** [comment]
Closed by #109
