### ISSUE TITLE
Download fails with large un-cached dataset

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#123]
1. Let S3 cache expire
2. Try to download https://testhub.dronedb.app/r/HeDo88/cascina

Witness: 
```
{"error":"Array dimensions exceeded supported range."}
```

**Comment by HeDo88TH** [comment]
```
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
   at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Compression.CheckSumAndSizeWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Registry.Adapters.ObjectSystem.CachedS3ObjectSystem.GetObjectAsync(String bucketName, String objectName, Action`1 callback, IServerEncryption sse, CancellationToken cancellationToken) in /Registry/Registry.Adapters/ObjectSystem/CachedS3ObjectSystem.cs:line 515
2021-02-16T17:56:15.7770752+01:00 0HM69TAEB24S2:00000003 [ERR] Exception in Objects controller Download('HeDo88', 'cascina', '') (805ed16a)
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at System.IO.Compression.ZipArchive.Dispose()
   at Registry.Web.Services.Adapters.ObjectsManager.GetFileDescriptor(String orgSlug, String dsSlug, Guid internalRef, String[] paths) in /Registry/Registry.Web/Services/Adapters/ObjectsManager.cs:line 671
   at Registry.Web.Services.Adapters.ObjectsManager.Download(String orgSlug, String dsSlug, String[] paths) in /Registry/Registry.Web/Services/Adapters/ObjectsManager.cs:line 586
   at Registry.Web.Controllers.ObjectsController.Download(String orgSlug, String dsSlug, String pathsRaw, Nullable`1 isInlineRaw) in /Registry/Registry.Web/Controllers/ObjectsController.cs:line 98
```
