### ISSUE TITLE
Cannot push to Registry

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#133]
- Clone a dataset with a single file:

`ddb clone http://localhost:5000/admin/test`

- Navigate to folder, try to push:

`cd test && ddb push`

```
[piero:/data/regtest/test] $ ddb push
Push using tag 'http://localhost:5000/admin/test', last sync 1618498271, dataset mtime 1618498094
Zipping ddb folder
Initializing push
Transfers done
Error response from registry: Could not find a part of the path '/home/piero/Documents/Registry/Registry.Web/temp/admin-10bfa83c-bcbd-4b30-b916-739b9d0a4c5e/.tmp'.
```

**Comment by pierotofy** [comment]
Also probably related:

```
ddb push
Pushing to 'http://localhost:5000/admin/test'
Zipping ddb folder
Initializing push
Transfers done
Error response from registry: File 'abc' does not exist
```

Not sure how I reproduced this one.

**Comment by pierotofy** [comment]
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Entity Framework Core 5.0.1 initialized 'RegistryContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executed DbCommand (1ms) [Parameters=[@__orgSlug_0='admin' (Size = 5)], CommandType='Text', CommandTimeout='30']
      SELECT "t"."Slug", "t"."CreationDate", "t"."Description", "t"."IsPublic", "t"."Name", "t"."OwnerId", "d"."Id", "d"."CreationDate", "d"."Description", "d"."InternalRef", "d"."Name", "d"."ObjectsCount", "d"."OrganizationSlug", "d"."PasswordHash", "d"."Size", "d"."Slug"
      FROM (
          SELECT "o"."Slug", "o"."CreationDate", "o"."Description", "o"."IsPublic", "o"."Name", "o"."OwnerId"
          FROM "Organizations" AS "o"
          WHERE "o"."Slug" = @__orgSlug_0
          LIMIT 1
      ) AS "t"
      LEFT JOIN "Datasets" AS "d" ON "t"."Slug" = "d"."OrganizationSlug"
      ORDER BY "t"."Slug", "d"."Id"
info: Registry.Web.Services.Managers.DdbManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Opened ddb in './ddbstore/admin/10bfa83c-bcbd-4b30-b916-739b9d0a4c5e'
2021-04-19 08:57:45.241 DEBUG [191808] [ddb::open@43] /home/piero/Documents/Registry/Registry.Web/./ddbstore/admin/10bfa83c-bcbd-4b30-b916-739b9d0a4c5e/.ddb/dbase.sqlite exists
2021-04-19 08:57:45.241 DEBUG [191808] [ddb::SqliteDatabase::open@19] Opening connection to /home/piero/Documents/Registry/Registry.Web/./ddbstore/admin/10bfa83c-bcbd-4b30-b916-739b9d0a4c5e/.ddb/dbase.sqlite
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "entries" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [ddb::Database::ensureSchemaConsistency@75] Ensuring schema consistency
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "entries" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "passwords" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "attributes" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT COUNT(name) FROM attributes WHERE name = ?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "public" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT ivalue FROM attributes WHERE name = ?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "public" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT ivalue FROM attributes WHERE name = ?
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::bind@35] Bind "mtime" as param 1
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::Statement@16] Statement: SELECT path FROM entries WHERE path = 'LICENSE.md' OR path = 'README.md'
2021-04-19 08:57:45.244 DEBUG [191808] [Statement::~Statement@27] Destroying statement: 0x7f1a5407cbf0
2021-04-19 08:57:45.244 DEBUG [191808] [ddb::SqliteDatabase::close@42] Closing connection to /home/piero/Documents/Registry/Registry.Web/./ddbstore/admin/10bfa83c-bcbd-4b30-b916-739b9d0a4c5e/.ddb/dbase.sqlite
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Entity Framework Core 5.0.1 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: SensitiveDataLoggingEnabled 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executed DbCommand (0ms) [Parameters=[@__p_0='29ddc113-1291-4cf9-acfd-b7cb19155141' (Size = 36)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."Id", "a"."AccessFailedCount", "a"."ConcurrencyStamp", "a"."Email", "a"."EmailConfirmed", "a"."LockoutEnabled", "a"."LockoutEnd", "a"."Metadata", "a"."NormalizedEmail", "a"."NormalizedUserName", "a"."PasswordHash", "a"."PhoneNumber", "a"."PhoneNumberConfirmed", "a"."SecurityStamp", "a"."TwoFactorEnabled", "a"."UserName"
      FROM "AspNetUsers" AS "a"
      WHERE "a"."Id" = @__p_0
      LIMIT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executed DbCommand (0ms) [Parameters=[@__normalizedRoleName_0='ADMIN' (Size = 5)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."Id", "a"."ConcurrencyStamp", "a"."Name", "a"."NormalizedName"
      FROM "AspNetRoles" AS "a"
      WHERE "a"."NormalizedName" = @__normalizedRoleName_0
      LIMIT 2
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executed DbCommand (0ms) [Parameters=[@__p_0='29ddc113-1291-4cf9-acfd-b7cb19155141' (Size = 36), @__p_1='940308c6-cddc-42df-a887-62193993d4e2' (Size = 36)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."UserId", "a"."RoleId"
      FROM "AspNetUserRoles" AS "a"
      WHERE ("a"."UserId" = @__p_0) AND ("a"."RoleId" = @__p_1)
      LIMIT 1
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Moving copies to temp folder 
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      CPY -> abc/123/aaa.txt TO a.txt
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Changed copy path from abc/123/aaa.txt to .tmp/abc/123/aaa.txt
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Working on removes
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Working on adds
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Working on direct copies
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      CPY -> .tmp/abc/123/aaa.txt TO a.txt
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Dest file exists, writing shadow
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Working on shadow copies
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      CPY -> .tmp/abc/123/aaa.txt TO a.txt
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Shadow file exists, replacing original one
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Clearing temp folder
fail: Registry.Web.Controllers.PushController[0]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Exception in Push controller Commit('admin', 'test')
      System.ArgumentException: File 'abc' does not exist
         at Registry.Adapters.ObjectSystem.PhysicalObjectSystem.EnsureFileExists(String path) in /home/piero/Documents/Registry/Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs:line 607
         at Registry.Adapters.ObjectSystem.PhysicalObjectSystem.EnsureObjectExists(String bucketName, String objectName) in /home/piero/Documents/Registry/Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs:line 478
         at Registry.Adapters.ObjectSystem.PhysicalObjectSystem.RemoveObjectAsync(String bucketName, String objectName, CancellationToken cancellationToken) in /home/piero/Documents/Registry/Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs:line 105
         at Registry.Web.Services.Managers.PushManager.ApplyDelta(String bucketName, DeltaDto delta, String addTempFolder) in /home/piero/Documents/Registry/Registry.Web/Services/Managers/PushManager.cs:line 327
         at Registry.Web.Services.Managers.PushManager.Commit(String orgSlug, String dsSlug) in /home/piero/Documents/Registry/Registry.Web/Services/Managers/PushManager.cs:line 151
         at Registry.Web.Controllers.PushController.Commit(String orgSlug, String dsSlug) in /home/piero/Documents/Registry/Registry.Web/Controllers/PushController.cs:line 87
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executing BadRequestObjectResult, writing value of type 'Registry.Web.Models.ErrorResponse'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Executed action Registry.Web.Controllers.PushController.Commit (Registry.Web) in 14.1092ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002
      Executed endpoint 'Registry.Web.Controllers.PushController.Commit (Registry.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      => SpanId:ebfbdff3b8164841, TraceId:655b7901aa19754ba9db5a6b30666186, ParentId:0000000000000000 => ConnectionId:0HM811R3BCC60 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM811R3BCC60:00000002
```
