### ISSUE TITLE
Cannot share on Registry (Windows only)

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#135]
Using the `push-pull` PRs for both Registry and the DDB client, when I issue:

```
ddb share test.txt -t http://192.168.2.251:5000/admin/test
```

I get:

```
[piero:/data/test] 1 $ ddb share test.txt -t http://192.168.2.251:5000/admin/test

Error response from registry: Attributes is null
```

```
info: Registry.Web.Services.Managers.DdbManager[0]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002 => Registry.Web.Controllers.ShareController.Init (Registry.Web)
      Initialized new ddb in './ddbstore\admin\b2fdd00b-291a-4205-a43c-70b2b16d3d9f'
fail: Registry.Web.Controllers.ShareController[0]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002 => Registry.Web.Controllers.ShareController.Init (Registry.Web)
      Exception in Share controller Init('Registry.Web.Models.DTO.ShareInitDto')
      System.ArgumentException: Attributes is null
         at DDB.Bindings.DroneDB.ChangeAttributes(String ddbPath, Dictionary`2 attributes)
         at Registry.Adapters.DroneDB.Ddb.ChangeAttributesRaw(Dictionary`2 attributes) in D:\Registry\Registry.Adapters.DroneDB\Ddb.cs:line 162
         at Registry.Web.Services.Managers.DatasetsManager.AddNew(String orgSlug, DatasetDto dataset) in D:\Registry\Registry.Web\Services\Managers\DatasetsManager.cs:line 104
         at Registry.Web.Services.Managers.ShareManager.Initialize(ShareInitDto parameters) in D:\Registry\Registry.Web\Services\Managers\ShareManager.cs:line 268
         at Registry.Web.Controllers.ShareController.Init(ShareInitDto parameters) in D:\Registry\Registry.Web\Controllers\ShareController.cs:line 47
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002 => Registry.Web.Controllers.ShareController.Init (Registry.Web)
      Executing BadRequestObjectResult, writing value of type 'Registry.Web.Models.ErrorResponse'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002 => Registry.Web.Controllers.ShareController.Init (Registry.Web)
      Executed action Registry.Web.Controllers.ShareController.Init (Registry.Web) in 200.8443ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002
      Executed endpoint 'Registry.Web.Controllers.ShareController.Init (Registry.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      => SpanId:b84ae84299e63a42, TraceId:9b5e592b1afffb4bafeee1d2fde90df2, ParentId:0000000000000000 => ConnectionId:0HM811K2AT5TO => RequestPath:/share/init RequestId:0HM811K2AT5TO:00000002
      Request finished HTTP/1.1 POST http://192.168.2.251:5000/share/init application/x-www-form-urlencoded 15 - 400 30 application/json;+charset=utf-8 201.6877ms
```

Fresh clone of Registry, using the latest ddb lib:

```
D:\Registry>dotnet run --project Registry.Web --urls http://0.0.0.0:5000
 !> Using DDB version 0.9.9 (git commit 8ff44c8)
```

Works fine on Linux.

**Comment by pierotofy** [comment]
Fixed!
