### ISSUE TITLE
Cannot push on Registry if Registry is installed on D: (Windows + Linux)

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#137]
To reproduce:

1. Create a dataset
2. Clone it
3. Add a file (`ddb add test.txt`)
4. Issue: `ddb push`

Witness:

```
 C:\Users\pt\AppData\Local\Temp\push\admin\test\ddb
info: Registry.Web.Services.Managers.PushManager[0]
      => SpanId:0b8246c9f07c7048, TraceId:198cab5b1aff824c903256099f981bb0, ParentId:0000000000000000 => ConnectionId:0HM83B4B49DM7 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM83B4B49DM7:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      ./ddbstore\admin\1c43f0f4-23f6-43bf-bf1f-b86cefa1d7f6
fail: Registry.Web.Controllers.PushController[0]
      => SpanId:0b8246c9f07c7048, TraceId:198cab5b1aff824c903256099f981bb0, ParentId:0000000000000000 => ConnectionId:0HM83B4B49DM7 => RequestPath:/orgs/admin/ds/test/push/commit RequestId:0HM83B4B49DM7:00000002 => Registry.Web.Controllers.PushController.Commit (Registry.Web)
      Exception in Push controller Commit('admin', 'test')
      System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
         at System.IO.Directory.Move(String sourceDirName, String destDirName)
         at Registry.Web.Services.Managers.PushManager.Commit(String orgSlug, String dsSlug) in D:\Registry\Registry.Web\Services\Managers\PushManager.cs:line 159
         at Registry.Web.Controllers.PushController.Commit(String orgSlug, String dsSlug) in D:\Registry\Registry.Web\Controllers\PushController.cs:line 87
```

**Comment by pierotofy** [comment]
`./ddbstore\admin\1c43f0f4-23f6-43bf-bf1f-b86cefa1d7f6` is in `D:` in this case.

**Comment by pierotofy** [comment]
This happens on Linux also:

```
      Exception in Push controller Commit('admin', 'test33')
      System.IO.IOException: Invalid cross-device link
         at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
         at System.IO.Directory.Move(String sourceDirName, String destDirName)
         at Registry.Web.Services.Managers.PushManager.Commit(String orgSlug, String dsSlug) in /home/piero/Documents/Registry/Registry.Web/Services/Managers/PushManager.cs:line 156
         at Registry.Web.Controllers.PushController.Commit(String orgSlug, String dsSlug) in /home/piero/Documents/Registry/Registry.Web/Controllers/PushController.cs:line 87
```

In this case, the data to be pushed is on a different device / hard drive than Registry.

```
[piero:/data/test/test33] $ ddb push
Pushing to 'http://localhost:5000/admin/test33'
Zipping ddb folder
Initializing push
Transfers done
Error response from registry: Invalid cross-device link
```
