### ISSUE TITLE
Docker image is broken

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#180]
```
C:\> docker run -ti --rm -p 5000:5000 -p 5001:5001 dronedb/registry

info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server using job storage: 'Hangfire.InMemory.InMemoryStorage'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
          Worker count: 10
          Listening queues: 'default'
          Shutdown timeout: 00:00:15
          Schedule polling interval: 00:00:15
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda successfully announced in 2.0119 ms
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, Worker, DelayedJobScheduler, RecurringJobScheduler...
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda all the dispatchers started
warn: Microsoft.EntityFrameworkCore.Model.Validation[10620]
      The property 'Metadata.User' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10620]
      The property 'Paths.DownloadPackage' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
      For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda caught stopping signal...
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda caught stopped signal...
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda All dispatchers stopped
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda successfully reported itself as stopped in 0.4257 ms
info: Hangfire.Server.BackgroundServerProcess[0]
      Server 0dbb050e2cbd:7:113d8fda has been stopped in total 3.8711 ms
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Registry.Web.Program.Main(String[] args) in /Registry/Registry.Web/Program.cs:line 56
Aborted
```

**Comment by pierotofy** [comment]
As a side note, it's also really large (1.3GB).

**Comment by HeDo88TH** [comment]
> As a side note, it's also really large (1.3GB).

I know both, that's why I'm slowing down the hub deployment. I will hotfix in https://github.com/DroneDB/Registry/pull/181
